FROM php:8.2-fpm-alpine

WORKDIR /var/www/html

RUN apk --no-cache add \
    bash \
    git \
    unzip \
    libzip-dev \
    && docker-php-ext-install zip pdo_mysql

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY . .

RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html/storage